FROM python:3.11.9-slim

RUN apt-get update && apt-get install -y curl build-essential
RUN pip install --no-cache-dir poetry

WORKDIR /app

RUN poetry config virtualenvs.create false --local
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-interaction --no-ansi

COPY . .

EXPOSE 9020

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9020"]
