services:
  chromadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMADB_PERSIST_DIRECTORY=/app/chroma_db_data
    volumes:
      - chromadb_data:/app/chroma_db_data

volumes:
  chromadb_data:
