services:
  chromadb:
    build:
      context: ./src/chromadb
      dockerfile: Dockerfile
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMADB_PERSIST_DIRECTORY=/app/chroma_db_data
    volumes:
      - chromadb_data:/app/chroma_db_data

  fastapi:
    build:
      context: ./src/fastapi
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_service
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - chromadb
    volumes:
      - ./src/fastapi/pyproject.toml:/app/pyproject.toml
      - ./src/fastapi/poetry.lock:/app/poetry.lock

  streamlit:
    build:
      context: ./src/streamlit_app
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - chromadb
      - fastapi
    volumes:
      - ./src/streamlit_app/pyproject.toml:/app/pyproject.toml
      - ./src/streamlit_app/poetry.lock:/app/poetry.lock


volumes:
  chromadb_data:
