services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adminpassword}
      POSTGRES_DB: ${POSTGRES_DB:-jitc_gen_ai_db}
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    container_name: chroma
    image: ghcr.io/chroma-core/chroma:3.5
    environment:
      CHROMA_API_IMPL: chromadb.api.fastapi.FastAPI
      CHROMA_DB_IMPL: chromadb.db.postgresql.PostgresDB
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adminpassword}
      POSTGRES_DB: ${POSTGRES_DB:-chroma_db}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./volumes/chroma:/chroma_data
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - postgres
      - chroma

networks:
  default:
    name: jitc_gen_ai_db_network
