services:
  chromadb:
    build:
      context: ./src/chromadb
      dockerfile: Dockerfile
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMADB_PERSIST_DIRECTORY=/app/chroma_db_data
    volumes:
      - chromadb_data:/app/chroma_db_data

  fastapi:
    build:
      context: ./src/fastapi
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    ports:
      - "9000:9000"
    env_file:
      - .env  
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_API_KEY}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
    depends_on:
      - chromadb
    volumes:
      - ./src/fastapi/pyproject.toml:/app/pyproject.toml
      - ./src/fastapi/poetry.lock:/app/poetry.lock
  streamlit:
    build:
      context: .
      dockerfile: src/streamlit_app/Dockerfile.streamlit
      args:
        HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY} 
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - chromadb
      - fastapi
    env_file:
      - .env  
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_API_KEY} 
    volumes:
      - ./src/streamlit_app/pyproject.toml:/app/pyproject.toml
      - ./src/streamlit_app/poetry.lock:/app/poetry.lock


volumes:
  chromadb_data:
